from typing import TypeAlias

from ._types import Number
from .base import matrix, spmatrix

BLASArg: TypeAlias = Number | matrix | spmatrix | str


def asum(*args: BLASArg, **kwargs: BLASArg) -> float: ...
def axpy(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def copy(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def dot(*args: BLASArg, **kwargs: BLASArg) -> Number: ...
def dotu(*args: BLASArg, **kwargs: BLASArg) -> Number: ...
def gbmv(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def gemm(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def gemv(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def ger(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def geru(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def hbmv(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def hemm(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def hemv(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def her(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def her2(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def her2k(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def herk(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def iamax(*args: BLASArg, **kwargs: BLASArg) -> int: ...
def nrm2(*args: BLASArg, **kwargs: BLASArg) -> float: ...
def sbmv(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def scal(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def swap(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def symm(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def symv(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def syr(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def syr2(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def syr2k(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def syrk(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def tbmv(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def tbsv(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def trmm(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def trmv(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def trsm(*args: BLASArg, **kwargs: BLASArg) -> None: ...
def trsv(*args: BLASArg, **kwargs: BLASArg) -> None: ...
