from ._types import FactorHandle, OptionValue, Uplo
from .base import matrix, spmatrix

options: dict[str, OptionValue]


def symbolic(A: spmatrix, p: matrix | None = ..., uplo: Uplo = ...) -> FactorHandle: ...
def numeric(A: spmatrix, F: FactorHandle) -> None: ...
def solve(F: FactorHandle, B: matrix, sys: int = ..., nrhs: int = ..., ldB: int = ..., offsetB: int = ...) -> None: ...
def spsolve(F: FactorHandle, B: spmatrix, sys: int = ...) -> spmatrix: ...
def linsolve(A: spmatrix, B: matrix, p: matrix | None = ..., uplo: Uplo = ..., nrhs: int = ..., ldB: int = ..., offsetB: int = ...) -> None: ...
def splinsolve(A: spmatrix, B: spmatrix, p: matrix | None = ..., uplo: Uplo = ...) -> spmatrix: ...
def diag(F: FactorHandle) -> matrix: ...
def getfactor(F: FactorHandle) -> spmatrix: ...
