from ._types import Number, OptionValue
from .base import matrix, spmatrix

options: dict[str, OptionValue]


def normal(nrows: int, ncols: int = ..., mean: float = ..., std: float = ...) -> matrix: ...
def uniform(nrows: int, ncols: int = ..., a: float = ..., b: float = ...) -> matrix: ...
def weibull(nrows: int, ncols: int = ..., a: float = ..., b: float = ...) -> matrix: ...
def getseed() -> int: ...
def setseed(seed: int = ...) -> None: ...
def __getattr__(name: str) -> matrix | spmatrix | Number | dict[str, OptionValue]: ...
