from typing import TypeAlias

from ._types import Number
from .base import matrix, spmatrix

LapackArg: TypeAlias = Number | matrix | spmatrix | str | int
LapackRet: TypeAlias = None | int | float | complex | matrix | tuple[matrix, ...] | tuple[int, ...]


def gbsv(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def gbtrf(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def gbtrs(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def gees(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def gelqf(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def gels(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def geqp3(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def geqrf(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def gesdd(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def gesv(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def gesvd(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def getrf(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def getri(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def getrs(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def gges(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def gtsv(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def gttrf(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def gttrs(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def heev(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def heevd(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def heevr(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def heevx(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def hegv(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def hesv(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def hetrf(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def hetri(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def hetrs(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def lacpy(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def larfg(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def larfx(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def orglq(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def orgqr(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def ormlq(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def ormqr(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def pbsv(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def pbtrf(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def pbtrs(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def posv(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def potrf(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def potri(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def potrs(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def ptsv(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def pttrf(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def pttrs(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def syev(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def syevd(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def syevr(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def syevx(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def sygv(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def sysv(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def sytrf(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def sytri(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def sytrs(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def tbtrs(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def trtri(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def trtrs(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def unglq(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def ungqr(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def unmlq(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
def unmqr(*args: LapackArg, **kwargs: LapackArg) -> LapackRet: ...
