from ._types import Trans
from .base import Number, matrix


def scale(x: matrix, W: dict[str, matrix | list[matrix] | list[float]], trans: Trans = ..., inverse: str = ...) -> None: ...
def scale2(lmbda: matrix, x: matrix, dims: dict[str, int | list[int]], mnl: int = ..., inverse: str = ...) -> None: ...
def pack(x: matrix, y: matrix, dims: dict[str, int | list[int]], mnl: int = ..., offsetx: int = ..., offsety: int = ...) -> None: ...
def pack2(x: matrix, dims: dict[str, int | list[int]], mnl: int = ...) -> None: ...
def unpack(x: matrix, y: matrix, dims: dict[str, int | list[int]], mnl: int = ..., offsetx: int = ..., offsety: int = ...) -> None: ...
def symm(x: matrix, n: int, offset: int = ...) -> None: ...
def trisc(x: matrix, dims: dict[str, int | list[int]], offset: int = ...) -> None: ...
def triusc(x: matrix, dims: dict[str, int | list[int]], offset: int = ...) -> None: ...
def sdot(x: matrix, y: matrix, dims: dict[str, int | list[int]], mnl: int = ...) -> float: ...
def sprod(x: matrix, y: matrix, dims: dict[str, int | list[int]], mnl: int = ..., diag: str = ...) -> None: ...
def sinv(x: matrix, y: matrix, dims: dict[str, int | list[int]], mnl: int = ...) -> None: ...
def max_step(x: matrix, dims: dict[str, int | list[int]], mnl: int = ..., sigma: Number | None = ...) -> float: ...
