from .base import Number, matrix, spmatrix


def compute_scaling(s: matrix, z: matrix, lmbda: matrix, dims: dict[str, int | list[int]], mnl: int | None = ...) -> dict[str, matrix | list[matrix] | list[float]]: ...
def update_scaling(W: dict[str, matrix | list[matrix] | list[float]], lmbda: matrix, s: matrix, z: matrix) -> None: ...
def sdot2(x: matrix, y: matrix) -> float: ...
def snrm2(x: matrix, dims: dict[str, int | list[int]], mnl: int = ...) -> float: ...
def sgemv(A: matrix | spmatrix, x: matrix, y: matrix, dims: dict[str, int | list[int]], trans: str = ..., alpha: float = ..., beta: float = ..., n: int | None = ..., offsetA: int = ..., offsetx: int = ..., offsety: int = ...) -> None: ...
def jdot(x: matrix, y: matrix, n: int | None = ..., offsetx: int = ..., offsety: int = ...) -> float: ...
def jnrm2(x: matrix, n: int | None = ..., offset: int = ...) -> float: ...
def ssqr(x: matrix, y: matrix, dims: dict[str, int | list[int]], mnl: int = ...) -> None: ...
def kkt_ldl(G: matrix | spmatrix, dims: dict[str, int | list[int]], A: matrix | spmatrix, mnl: int = ..., kktreg: float | None = ...) -> matrix: ...
def kkt_ldl2(G: matrix | spmatrix, dims: dict[str, int | list[int]], A: matrix | spmatrix, mnl: int = ...) -> matrix: ...
def kkt_chol(G: matrix | spmatrix, dims: dict[str, int | list[int]], A: matrix | spmatrix, mnl: int = ...) -> matrix: ...
def kkt_chol2(G: matrix | spmatrix, dims: dict[str, int | list[int]], A: matrix | spmatrix, mnl: int = ...) -> matrix: ...
def kkt_qr(G: matrix | spmatrix, dims: dict[str, int | list[int]], A: matrix | spmatrix) -> matrix: ...
