from typing import TypeAlias

from ._types import OptionValue, SolverStatus
from .base import matrix, spmatrix

SolverValue: TypeAlias = SolverStatus | matrix | spmatrix | list[matrix] | float | int | dict[str, OptionValue] | None
SolverResult: TypeAlias = dict[str, SolverValue]


def streamprinter(text: str) -> None: ...
def lp(c: matrix, G: matrix | spmatrix, h: matrix, A: matrix | spmatrix | None = ..., b: matrix | None = ..., taskfile: str | None = ..., **kwargs: OptionValue) -> SolverResult: ...
def conelp(c: matrix, G: matrix | spmatrix, h: matrix, dims: dict[str, OptionValue] | None = ..., taskfile: str | None = ..., **kwargs: OptionValue) -> SolverResult: ...
def socp(c: matrix, Gl: matrix | spmatrix | None = ..., hl: matrix | None = ..., Gq: list[matrix | spmatrix] | None = ..., hq: list[matrix] | None = ..., taskfile: str | None = ..., **kwargs: OptionValue) -> SolverResult: ...
def qp(P: matrix | spmatrix, q: matrix, G: matrix | spmatrix | None = ..., h: matrix | None = ..., A: matrix | spmatrix | None = ..., b: matrix | None = ..., taskfile: str | None = ..., **kwargs: OptionValue) -> SolverResult: ...
def ilp(c: matrix, G: matrix | spmatrix, h: matrix, A: matrix | spmatrix | None = ..., b: matrix | None = ..., I: set[int] | None = ..., taskfile: str | None = ..., **kwargs: OptionValue) -> SolverResult: ...
