from ._types import OptionValue
from .base import matrix, spmatrix

options: dict[str, OptionValue]


def matrix_str_default(X: matrix) -> str: ...
def matrix_repr_default(X: matrix) -> str: ...
def spmatrix_str_default(X: spmatrix) -> str: ...
def spmatrix_str_triplet(X: spmatrix) -> str: ...
def spmatrix_repr_default(X: spmatrix) -> str: ...
