from ._types import FactorHandle, Number, Trans
from .base import matrix, spmatrix


def symbolic(A: spmatrix) -> FactorHandle: ...
def numeric(A: spmatrix, Fs: FactorHandle) -> FactorHandle: ...
def linsolve(A: spmatrix, B: matrix, trans: Trans = ..., nrhs: int = ..., ldB: int = ..., offsetB: int = ...) -> None: ...
def solve(A: spmatrix, Fn: FactorHandle, B: matrix, trans: Trans = ..., nrhs: int = ..., ldB: int = ..., offsetB: int = ...) -> None: ...
def get_numeric(A: spmatrix, Fn: FactorHandle, trans: Trans = ...) -> tuple[spmatrix, spmatrix, spmatrix, spmatrix, spmatrix]: ...
def get_det(A: spmatrix, Fs: FactorHandle, Fn: FactorHandle) -> Number: ...
